### ISSUE TITLE
No output folder

### ISSUE THREAD

**Issue by tanalpha-aditya** [aalto-speech/Topic-identification-for-spontaneous-Finnish-speech#1]
i am getting this error while running any of the hyperparameter files

OSError: Not found: "output_folder/tokenizer/1000_unigram.model": No such file or directory Error #2

please help me fix it

**Comment by Tetrix** [comment]
Hi, seems like the tokeniser is missing. I added it to `lp_asr/output_folder_ctc_aed/tokenizer`
Also keep in mind that the trained models are not in the repo since Github does not allow adding large files. If you need then, I can upload them for example to Zenodo

**Comment by Tetrix** [comment]
I added also a Zenodo link to the pre-trained models.
