### ISSUE TITLE
Help to acquire dataset

### ISSUE THREAD

**Issue by tanalpha-aditya** [aalto-speech/Topic-identification-for-spontaneous-Finnish-speech#2]
Can you help me get the dataset for this model, i found this KORP ( language bank of finland ) probably they had some dataset but it wasnt available to me. I need this for research purposes at **Speech Lab, International Institute of Information Technology, Hyderabad, INDIA**. @Tetrix. 

I have also mailed you for the same on the mail you provided on your github profile. I would really appreciate a quick response from your side. Thanks

**Comment by Tetrix** [comment]
I am not the owner of the data, but generally it should be freely available for research purposes from the Language Bank of Finland. You can try this link which will redirect you to the dataset location: https://www.kielipankki.fi/corpora/puhelahjat/
If you still have issues getting the dataset, you can contact Kielipankki and they will assist you.

**Comment by tanalpha-aditya** [comment]
can u please share a snippet or a sample of how your json files looked like. just to get an idea and not release the dataset.

**Comment by Tetrix** [comment]
Here is how the JSON is structured for the multitask model:

`{
    "file_id1": {
        "file_path": "path/to/wav1",
        "words": "transcript number one",
        "length": 4.301,
        "topic": "animal"
    },
    "file_id2": {
        "file_path": "path/to/wav2",
        "words": "transcript number two",
        "length": 2.301,
        "topic": "sport"
    }
}`

**Comment by tanalpha-aditya** [comment]
thanks a ton.
